Repository cnpem/sophys-common, pull requests merged in 2025-05, with the labels that each got.

#45 Support nested runs in Kafka monitor
  src/sophys/common/utils/kafka/monitor.py
  tests/utils/test_kafka_monitor.py
Labels: bug

#55 Fix Kinematic slits components
  src/sophys/common/devices/slit.py
Labels: bug

#58 Fix automated testing in CI with multiple Python versions
  .github/workflows/testing.yml
  pyproject.toml
  src/sophys/common/utils/packages.py
  tests/utils/test_packages.py
Labels: bug, CI

#61 Support numpy array encoding in kafka callback factory
  src/sophys/common/utils/kafka/callback.py
Labels: bug

#56 Add basic instantiation tests for Slits devices
  pyproject.toml
  src/sophys/common/devices/motor.py
  src/sophys/common/devices/slit.py
  tests/conftest.py
  tests/devices/test_picolo.py
  tests/devices/test_slits.py
  tests/soft_ioc.py
  tests/utils/test_kafka_monitor.py
Labels: enhancement
