Repository cnpem/sophys-common, pull requests merged in 2025-03, with the labels that each got.

#34 Correctly version package installed in CI
  .github/workflows/documentation.yml
  .github/workflows/pre-commit.yml
  .github/workflows/testing.yml
Labels: documentation, CI

#35 Directly include kafka callback in the documentation's utils callbacks section
  docs/source/utils.rst
Labels: documentation

#24 Fix various Pimega device issues with step scanning
  src/sophys/common/devices/pimega.py
Labels: bug, enhancement

#16 Fix virtual motors usage with newer Ophyd versions
  src/sophys/common/devices/__init__.py
  src/sophys/common/devices/motor.py
  src/sophys/common/devices/slit.py
Labels: bug, breaking change

#37 Add helper function to install packages via pip
  src/sophys/common/utils/pip.py
  tests/utils/test_pip.py
Labels: enhancement

#39 Update `tj-actions/changed-files` to latest version, without a security vulnerability
  .github/workflows/pre-commit.yml
Labels: CI

#36 Fix Picolo device to match IOC implementation
  src/sophys/common/devices/picolo.py
  src/sophys/common/utils/__init__.py
  src/sophys/common/utils/interfaces.py
  tests/test_picolo.py
Labels: bug, breaking change

#38 Add factory function for simulated Ophyd devices
  docs/source/devices_misc.rst
  src/sophys/common/devices/__init__.py
  src/sophys/common/devices/simulated.py
Labels: enhancement
